apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkedin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: linkedin
  template:
    metadata:
      labels:
        component: linkedin
    spec:
      containers:
      - name: linkedin-pod
        image: flagprotectors/linkedin:latest
        env:
          - name: SERVICE_HOST
            value: linkedin-clusterip
          - name: SERVICE_PORT
            value: "3001"
          - name: DATABASE_HOST
            value: database-clusterip
          - name: DATABASE_PORT
            value: "3100"
          - name: CLIENT_ID
            valueFrom: 
              secretKeyRef: 
                name: linkedin
                key:  CLIENT_ID
          - name: CLIENT_SECRET
            valueFrom: 
              secretKeyRef: 
                name: linkedin
                key:  CLIENT_SECRET
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: linkedin-clusterip
spec:
  type: ClusterIP
  selector:
    component: linkedin
  ports:
  - port: 3001
    targetPort: 5000